[package]
name = "sirius-halo2-gadget-migration"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/snarkify/sirius-halo2-gadget-migration"
license = "MIT"

[dependencies]
sirius = { git = "https://github.com/snarkify/sirius/", tag = "v0.1.1", version = "0.1.1" }
